---

#Variables for setting up PostgreSQL database for Lovelace main server

db_main_user: lovelace
db_main_user_password: lovelace
db_checker_user: auxchecker
db_checker_user_password: lovelace
db_main_database_name: lovelace

