- name: Start Server and install packages
  hosts: Lovelace
  become: yes
  become_user: root
  tasks:

    - name: Update repositories
      apt:
        update_cache: yes

    - name: Install PostGreSQL Server
      apt:
        name:
          - postgresql-12
          - postgresql-contrib
          - python3-pip
          - python3-dev
          - virtualenv
          - postgresql-client-12
      
- name: Server Configuration
  hosts: Lovelace
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  
  - name: Install psycopg2
    pip:
      name: psycopg2-binary
      state: latest

  - name: Edit PostGreSQL conf
    ansible.builtin.lineinfile:
      path: /etc/postgresql/12/main/postgresql.conf
      regexp: '^#listen_addresses = '
      line: listen_addresses = 'localhost,192.168.1.14'

  - name: Edit PostGreSQL pg_hba conf
    ansible.builtin.lineinfile:
      path: /etc/postgresql/12/main/pg_hba.conf
      regexp: '^#host '
      line: host    lovelace    lovelace    192.168.1.14/24 md5
      
  - name: Start and enable postgres on startup
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - postgresql
      
  - name: Create db user
    postgresql_user:
      state: present
      name: lovelace
      password: lovelace
    become: true
    become_user: postgres
      
  - name: Create Lovelace db
    postgresql_db:
      state: present
      #name: "{{ db_name }}"
      name: lovelace
    become: true
    become_user: postgres

  - name: Grant db user access to Lovelace db
    postgresql_privs:
      type: database
      #database: "{{ db_name }}"
      database: lovelace
      #roles: "{{ db_user }}"
      roles: postgres
      grant_option: no
      privs: all
    become: true
    become_user: postgres
    
  - name: Add Lovelace user
    ansible.builtin.user:
      name: lovelace
      group: sudo
      createhome: yes

- name: Lovelave configuration
  hosts: Lovelace
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:


  - name: Make lovelace directory
    ansible.builtin.file:
      path: /var/lovelace
      state: directory
      owner: lovelace
    
  - name: Git clone Lovelace to VM
    ansible.builtin.git:
      repo: 'https://github.com/miikkas/lovelace.git'
      dest: /var/lovelace
      
  - name: Install RabbitMQ server and Erlang
    apt:
      update_cache: yes
      name:
        - rabbitmq-server
        - redis
        - redis-server
        - libjpeg-turbo8-dev
      
  - name: Copy Requirements.txt to Lovelace
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '../requirements.txt', dest: '/home/lovelace/' }
      
  - name: Setup venv for Lovelace
    pip:
      virtualenv: /var/lovelace/venv
      requirements: /home/lovelace/requirements.txt
      virtualenv_python: python3.8
      
#  - name: Add Erlang to VM
#    get_url:
#        url: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
#        dest: /home/lovelace/
        
#  - name: Install Erlang
#      shell: dpkg -i /home/lovelace/erlang-solutions_2.0_all.deb
#      become: true
#      ignore_errors: yes
      
#  - name: Apt install Erlang
#    apt:
#      update_cache: yes
#      name:
#        - erlang
        
#  - name: Setup RabbitMQ
    
